apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: tcp
    port: 80
    targetPort: 80


    Error from server (BadRequest): error when creating "09-svc.yaml": Service in version "v1" cannot be handled 
    as a Service: strict decoding error: unknown field "spec.selectors"
